sudo: false
language: go

services:
- postgresql

addons:
  postgresql: "9.4"

go:
  - 1.4
  - 1.5
  - 1.6
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get gopkg.in/pg.v4
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in/go-pg
  - mv `pwd` $HOME/gopath/src/gopkg.in/go-pg/sharding.v4
