language: go

services:
- postgresql

addons:
  postgresql: "9.3"

go:
  - 1.3
  - 1.4
  - tip

install:
  - go get gopkg.in/pg.v3
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - mkdir -p $HOME/gopath/src/gopkg.in/go-pg
  - ln -s `pwd` $HOME/gopath/src/gopkg.in/go-pg/sharding.v1

before_script:
  - psql -c 'CREATE DATABASE test' -U postgres
